// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhndqomsquvtonxpnjmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZobmRxb21zcXV2dG9ueHBuam1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzExNzQsImV4cCI6MjA3MzQwNzE3NH0.01th_qbxncra6wsjTjm5-w8rQ8HHFdWhYBYpHAGo1lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});